name: Evaluate Emoji-gramming code
description: Simple GitHub Action that evaluates Emoji-gramming code
inputs:
  leaderboard:
    description: The file that stores the leaderboard data
    required: true
  input:
    description: The input for the program
    required: false
    default: ''
  expected-output:
    description: The expected output for the program
    required: false
    default: ''
  user:
    description: The user name
    required: true
  code:
    description: The Emoji-gramming code to evaluate
    required: true
  solution-url:
    description: HTML link to the solution
    required: true
outputs:
  success:
    description: Whether the evaluation completed normally or with error
  feedback:
    description: The feedback from the solution evaluation
runs:
  using: 'node12'
  main: 'index.js'
