name: Code golf
on:
  issue_comment:
    types: [created]
jobs:
  evaluate:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, '[contest]') && github.event.issue.state == 'open'
    timeout-minutes: 5
    steps:
    - id: add-comment
      name: Add comment
      uses: actions/github-script@v2
      with:
        script: |
          const issue_number = context.payload.issue.number;
          const comment_id = context.payload.comment.id;
          const comment_user = context.payload.comment.user.login;

          github.reactions.createForIssueComment({
            comment_id: comment_id,
            owner: context.repo.owner,
            repo: context.repo.repo,
            content: `eyes`
          });

          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `@${comment_user} your solution is correct.`
          });
        
