name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      uses: docker://adoptopenjdk/openjdk8:latest
      with:
        entrypoint: ./gradlew
        args: --no-daemon build
