name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        jdk: [11]
        inlcude:
          - jdk: x
    runs-on: ubuntu-latest

    name: Build on JDK ${{ matrix.jdk }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
        check-latest: true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
