name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v1
    - name: Add comment.
      id: add_comment
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const runId = parseInt(process.env['GITHUB_RUN_ID'] || '');
          if (Number.isNaN(runId)) return;
          const workflowRunResponse = await github.actions.getWorkflowRun({
            ...context.repo,
            run_id: runId
          });
          
          const checkSuiteUrl = workflowRunResponse.data.check_suite_url;
          const checkSuiteId = parseInt(checkSuiteUrl.match(/[0-9]+$/)[0], 10);
          const checkRunsResponse = await github.checks.listForSuite({
            ...context.repo,
            check_suite_id: checkSuiteId
          });
          const checkRun = checkRunsResponse.data.total_count > 0 && checkRunsResponse.data.check_runs[0]
          if (!checkRun) return;
          
          await github.checks.update({
            ...context.repo,
            check_run_id: checkRun.id,
            output: {
              title: 'Maven Build',
              summary: 'Build summary',
              text: 'Build Text',
              annotations: [
                {
                  path: '.github',
                  start_line: 1,
                  end_line: 1,
                  annotation_level: 'notice',
                  message: 'Annoation text',
                  title: 'Build complete',
                },
              ],
            },
          });
