name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get release version
      id: get_version
      uses: actions/github-script@master
      with:
        result-encoding: string
        script: |
          let ref = 'refs/tags/v1.0.0';
          let version = ref.replace('refs/tags/', '');
          if (version.startsWith('v')) {
              version = version.substr(1);
          }

          return version;
    - name: Run a one-line script
      env:
        VER: ${{ steps.get_version.outputs.result }}
      run: echo $VER
    - name: Run a one-line script
      env:
        NAME: World
      run: echo Hello $NAME
